
---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
- name: "Install Node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes
- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
  src: myenv.sh
  dest: /etc/profile.d/
# - name: "install python3."
#   become: true
#   apt:
#     name: ["python3"]
#     state: latest
#     update_cache: true

# - name: "upgrade packages"
#   become: true
#   apt:
#     upgrade: true

# - name: remove dependencies that are no longer required
#   become: true
#   apt:
#     autoremove: true

# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest

# - name: "install n (node version manager)"
#   become: true
#   npm:
#     name: n
#     global: true
#     production: true

# - name: "switch to node v13.8.0"
#   become: true
#   shell: n 13.8.0
  
# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: true
#     production: true
#     state: present
######################3
