
---
- name: "install python3."
  become: true
  apt:
    name: ["python3"]
    state: latest
    update_cache: true

- name: "upgrade packages"
  become: true
  apt:
    upgrade: true

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: true

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "install n (node version manager)"
  become: true
  npm:
    name: n
    global: true
    production: true

- name: "switch to node v13.8.0"
  become: true
  shell: n 13.8.0
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present