Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0    

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: ec2-ssh 
      ImageId: ami-068663a3c619dd892 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}

# Description: >heeeeeeeeer
#   UdaPeople backend stack.

# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String

# Resources:
#   InstanceSecurityGroup:
#     Type: AWS::EC2::SecurityGroup
#     Properties:
#       GroupName: !Sub UdaPeople-${ID}
#       GroupDescription: Allow port 22 and port 3030.
#       SecurityGroupIngress:
#         - IpProtocol: tcp
#           FromPort: 22
#           ToPort: 22
#           CidrIp: 0.0.0.0/0
#         - IpProtocol: tcp
#           FromPort: 3030
#           ToPort: 3030
#           CidrIp: 0.0.0.0/0
#         - IpProtocol: tcp
#           FromPort: 9100
#           ToPort: 9100
#           CidrIp: 0.0.0.0/0

#   EC2Instance:
#     Type: AWS::EC2::Instance
#     Properties:
#       InstanceType: t2.micro
#       SecurityGroups:
#         - Ref: InstanceSecurityGroup
#       KeyName: udacity
#       ImageId: ami-026b57f3c383c2eec
#       Tags:
#         - Key: Name
#           Value: !Sub backend-${ID}
  # InstanceEIP:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  #     InstanceId: !Ref EC2Instance